g="yo samuel, what's up?"
q="Yo Samuel, what's up?"
print(g.capitalize())
print(q.count("a"))
print(g.endswith("p"))
print(g.endswith("?"))
print(q.find("w"))
print(g.upper())
print(q.lower())
print(g.islower())
print(q.isupper())
print(g.isalpha())
print(q.isnumeric())
print(q.isspace())
print(g.isdecimal())
print(q.isprintable())